export const plots = {
  multipledose: {
    id: 'pk_mdmp_q2_mdplot',
    index: 2,
    title: 'Multiple Dosing Regimen Plot',
    header:
      'Drug X is an antibiotic with a therapeutic range between 20 and 40 mg/L. It is administered as an IV bolus. The population average for clearance and volume are 6 L/h and 85 L, respectively. Using the slider bars, explore how changes in dose and dosing interval impact achieving concentrations within the therapeutic window while maintaining an average steady-state concentration of 30 mg/L.',
    variables: [
      {
        name: 'Dose',
        units: 'mg',
        symbol: 'X_0',
        min: 500,
        max: 4500,
        value: 1000,
        step: 50,
      },
      {
        name: 'Number of Doses',
        units: '#',
        symbol: 'n',
        min: 4,
        max: 24,
        value: 4,
        step: 2,
      },
      {
        name: 'Volume of Distribution',
        units: 'L',
        symbol: 'V_D',
        min: 50,
        max: 500,
        value: 250,
        step: 5,
      },
      {
        name: 'Clearance',
        units: 'mL/min',
        symbol: 'Cl',
        min: 5,
        max: 50,
        value: 100,
        step: 5,
      },
      {
        name: 'Dosing Interval',
        units: 'hr',
        symbol: 'tau',
        min: 1,
        max: 7,
        value: 4,
        step: 1,
        range: [null, 4, 8, 12, 18, 24, 36, 48],
      },
    ],
    equation:
      '`(v["X_0"]/v["V_D"])*(1-2.71^(-n*0.06*(v["Cl"]/v["V_D"])*v["tau"]))/(1-2.71^(-0.06*(v["Cl"]/v["V_D"])*v["tau"]))*(2.71^(-0.06*(v["Cl"]/v["V_D"])*x))`',
    equationTemplate: '',
    multipleDose: true,
    bottomBound: 20,
    topBound: 40,
    axis: ['time (hr)', 'concentration (ug/L)'],
  },
  extravasation: {
    id: 'pk_akct_q1_scplot',
    title: 'Extravascular Administration',
    index: 1,
    header:
      'Move the slider bar to see the effects of clearance on the concentration-time profile. Concentration is related to time using the equation.',
    variables: [
      {
        name: 'Dose',
        units: 'mg',
        symbol: 'X_0',
        min: 250,
        max: 1000,
        value: 500,
        step: 50,
      },
      {
        name: 'Clearance',
        units: 'mL/min',
        symbol: 'Cl',
        min: 5,
        max: 50,
        value: 25,
        step: 5,
      },
      {
        name: 'Volume of Distribution',
        units: 'L',
        symbol: 'V_D',
        min: 50,
        max: 500,
        value: 250,
        step: 10,
      },
      {
        name: 'k<sub>a</sub>',
        units: '1/h',
        symbol: 'k_a',
        min: 0.1,
        max: 1,
        value: 0.5,
        step: 0.05,
      },
    ],
    equation:
      '`(v["k_a"]*v["X_0"])/(v["V_D"]*v["k_a"]-(0.06*v["Cl"]/v["V_D"]))*(2.71^(-(0.06*v["Cl"]/v["V_D"])*x)-2.71^(-v["k_a"]*x))`',
    equationTemplate: '`C = `',
    axis: ['time (min)', 'drug X(mg/L)'],
    multipleDose: false,
  },
};
