import './components/header/header.adapter';
import { NavComponent } from './components/navigation/nav.component';
import { HicksCardContainer } from './components/card/card-container.component';
import { HicksCard } from './components/card/card.component';
import { PlotEngine } from './components/plot/plot.component';
import { BrandComponent } from './components/brand/brand.component';
import { LogoComponent } from './components/brand/logo/logo.component';
import { ResponsiveLogo } from './components/brand/logo/responsive-logo.component';
import { NavItemComponent } from './components/navigation/nav-item.component';
import './components/toc/hicks-grid.component';
import './components/contact-me/contact.component';
import './components/expansion-panel/expansion-panel.component';
import './components/toggle/menu-toggle.adapter';
import './components/content/content.adapter';
import './components/resume/unlock-form/unlock-resume.component';
import './components/resume/resume-entry.adapter';
import './components/toc/toc-item.component';
import './components/toc/toc.adapter';
//Table of contents
NavItemComponent;
NavComponent;
HicksCardContainer;
HicksCard;
PlotEngine;
LogoComponent;
BrandComponent;
ResponsiveLogo;

import './global-logic';
import './sections/about-me.section';
import './sections/contact.section';
import './sections/portfolio.section';
import './sections/resume.section';
